import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavigationBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Moodic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>   
        {children}
        </body>
    </html>
  );
}
